### ISSUE TITLE
When will you fix the illegal copy?

### ISSUE THREAD

**Issue by dora2-iOS** [parrotgeek1/Pluvia#45]
This commit of you infringes my copyright: https://github.com/parrotgeek1/Pluvia/blob/d0f3beea193960cacb9fea3d5a56cf84367dad23/ramdisk_add/ramdiskH_beta4.dmg
It was copied and incorporated into the tool without permission before it was licensed. Unlicensed is not in the public domain.  I've pointed it out for two and a half years, but it never got fixed.

**Comment by parrotgeek1** [comment]
I will replace the copy of the exploit with the exploit from ch3rryflower, which is under GPL, as soon as possible. 
I apologize for not addressing this sooner.

https://archive.is/xk2tP
https://archive.is/E4SqF

**Comment by dora2-iOS** [comment]
No.  That exploit is not gplv3.

**Comment by parrotgeek1** [comment]
Legally, the fact that you committed that license file to that repository determines that all content of the repository is under GPLv3.

**Comment by dora2-iOS** [comment]
This is the only code licensed under the gplv3: https://github.com/dora2-iOS/B3nto

**Comment by parrotgeek1** [comment]
You cannot claim that code which literally has a GPLv3 license attached to it is not GPLv3.

**Comment by dora2-iOS** [comment]
I forgot to write it an exception, but the code was included on the "iloader" of my project. You can't use it.

**Comment by parrotgeek1** [comment]
The fact that you forgot to write an exception is irrelevant from a legal perspective. The only relevant fact is that you *didn't* write an exception, and therefore that file is GPLv3. There is nothing you can do to relicense code that has already been released.

**Comment by dora2-iOS** [comment]
No.  The base of cherryflower is made up of it.  The exploit license is free to use "other than you". I'm not you, so you can introduce the code without a license exclusion. This is because the display at the time of use is not obligatory.

**Comment by parrotgeek1** [comment]
I don't understand what that means, and anyway your reasoning has no legal basis. I'm locking this issue.

**Comment by parrotgeek1** [comment]
I hate to be like this, but I'm forced to because it really seems like you are trying to use your misconceptions of how licensing works to force me to delete Pluvia. 

The fact is, **you have licensed that ramdisk from ch3rryfl0wer under GPLv3**, regardless of whether you claim you intended to, or change it later. Code relicensing does not take effect retroactively.

I will be replacing the ramdisk, but I will not be discussing this issue any further. Please stop trying to sabotage this project. I gave you credit a long time ago.
